--------------------------------------------------------
--  File created - Thursday-November-13-2025   
--------------------------------------------------------
DROP TABLE "ABIR"."CLIENT" cascade constraints;
DROP TABLE "ABIR"."CREATEUR" cascade constraints;
DROP TABLE "ABIR"."DEVELOPPER" cascade constraints;
DROP TABLE "ABIR"."EMPLOYE" cascade constraints;
DROP TABLE "ABIR"."FINANCER" cascade constraints;
DROP TABLE "ABIR"."MATERIEL" cascade constraints;
DROP TABLE "ABIR"."PROJET" cascade constraints;
DROP TABLE "ABIR"."SPONSOR" cascade constraints;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "ABIR"."CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"ENTREPRISE" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"ID_EMPLOYE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CREATEUR
--------------------------------------------------------

  CREATE TABLE "ABIR"."CREATEUR" 
   (	"ID_CREATEUR" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"PSEUDO" VARCHAR2(50 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"RESEAU" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEVELOPPER
--------------------------------------------------------

  CREATE TABLE "ABIR"."DEVELOPPER" 
   (	"ID_CREATEUR" NUMBER, 
	"ID_PROJET" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "ABIR"."EMPLOYE" 
   (	"ID_EMPLOYE" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"POSTE" VARCHAR2(50 BYTE), 
	"TELEPHONE" NUMBER(8,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"COMPETENCE" VARCHAR2(100 BYTE), 
	"MOT_DE_PASSE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FINANCER
--------------------------------------------------------

  CREATE TABLE "ABIR"."FINANCER" 
   (	"ID_SPONSOR" NUMBER, 
	"ID_PROJET" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIEL
--------------------------------------------------------

  CREATE TABLE "ABIR"."MATERIEL" 
   (	"ID_MATERIEL" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"ETAT" VARCHAR2(50 BYTE), 
	"LOCALISATION" VARCHAR2(100 BYTE), 
	"ID_PROJET" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROJET
--------------------------------------------------------

  CREATE TABLE "ABIR"."PROJET" 
   (	"ID_PROJET" NUMBER, 
	"TYPE" VARCHAR2(50 BYTE), 
	"DATE_D" DATE, 
	"DATE_F" DATE, 
	"ID_CLIENT" NUMBER, 
	"PAIMENT" VARCHAR2(20 BYTE), 
	"MONTANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPONSOR
--------------------------------------------------------

  CREATE TABLE "ABIR"."SPONSOR" 
   (	"ID_SPONSOR" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"DETAILS" VARCHAR2(500 BYTE), 
	"DATE_DEBUT" DATE, 
	"CONTACT" VARCHAR2(100 BYTE), 
	"DATE_FIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ABIR.CLIENT
SET DEFINE OFF;
Insert into ABIR.CLIENT (ID_CLIENT,NOM,PRENOM,ENTREPRISE,EMAIL,TYPE,ID_EMPLOYE) values (2555555,'ABCff','AAAAA6','AAAAA','AAAAA.@gmail.com','entreprise',null);
Insert into ABIR.CLIENT (ID_CLIENT,NOM,PRENOM,ENTREPRISE,EMAIL,TYPE,ID_EMPLOYE) values (12345,'hhhh','nnnn','pppppppp','chahed.@gmail.com','entreprise',null);
Insert into ABIR.CLIENT (ID_CLIENT,NOM,PRENOM,ENTREPRISE,EMAIL,TYPE,ID_EMPLOYE) values (12345678,'aaa','bbb','lotf','lotf@gmail.com','entreprise',null);
REM INSERTING into ABIR.CREATEUR
SET DEFINE OFF;
REM INSERTING into ABIR.DEVELOPPER
SET DEFINE OFF;
REM INSERTING into ABIR.EMPLOYE
SET DEFINE OFF;
Insert into ABIR.EMPLOYE (ID_EMPLOYE,NOM,PRENOM,POSTE,TELEPHONE,EMAIL,COMPETENCE,MOT_DE_PASSE) values (22222222,'olfa','olfa','Client',22222222,'olfa@olfa.com','Avancé','olfa@olfa.com');
Insert into ABIR.EMPLOYE (ID_EMPLOYE,NOM,PRENOM,POSTE,TELEPHONE,EMAIL,COMPETENCE,MOT_DE_PASSE) values (22222223,'abir','olfa','Staff technique',22222222,'olfa@olfa.com','Intermédiaire','olfa@olfa.com');
REM INSERTING into ABIR.FINANCER
SET DEFINE OFF;
REM INSERTING into ABIR.MATERIEL
SET DEFINE OFF;
Insert into ABIR.MATERIEL (ID_MATERIEL,NOM,TYPE,ETAT,LOCALISATION,ID_PROJET) values (111,'aaa','Video','en panne','studio tournage',null);
Insert into ABIR.MATERIEL (ID_MATERIEL,NOM,TYPE,ETAT,LOCALISATION,ID_PROJET) values (222,'aazf','Video','fonctionnel','studio tournage',null);
Insert into ABIR.MATERIEL (ID_MATERIEL,NOM,TYPE,ETAT,LOCALISATION,ID_PROJET) values (333,'eef','Audio','hors service','salle montage',null);
Insert into ABIR.MATERIEL (ID_MATERIEL,NOM,TYPE,ETAT,LOCALISATION,ID_PROJET) values (444,'erfe','Matériel Live','en maintenance','salle podcast',null);
REM INSERTING into ABIR.PROJET
SET DEFINE OFF;
Insert into ABIR.PROJET (ID_PROJET,TYPE,DATE_D,DATE_F,ID_CLIENT,PAIMENT,MONTANT) values (111,'podcast',to_date('01-SEP-00','DD-MON-RR'),to_date('01-AUG-04','DD-MON-RR'),null,'virement ',28888);
Insert into ABIR.PROJET (ID_PROJET,TYPE,DATE_D,DATE_F,ID_CLIENT,PAIMENT,MONTANT) values (221,'podcast',to_date('01-JAN-00','DD-MON-RR'),to_date('01-AUG-00','DD-MON-RR'),null,'cash',222);
REM INSERTING into ABIR.SPONSOR
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007039
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."SYS_C007039" ON "ABIR"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007041
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."SYS_C007041" ON "ABIR"."CREATEUR" ("ID_CREATEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DEVELOPPER
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."PK_DEVELOPPER" ON "ABIR"."DEVELOPPER" ("ID_CREATEUR", "ID_PROJET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007044
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."SYS_C007044" ON "ABIR"."EMPLOYE" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_FINANCER
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."PK_FINANCER" ON "ABIR"."FINANCER" ("ID_SPONSOR", "ID_PROJET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007043
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."SYS_C007043" ON "ABIR"."MATERIEL" ("ID_MATERIEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007045
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."SYS_C007045" ON "ABIR"."PROJET" ("ID_PROJET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007040
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."SYS_C007040" ON "ABIR"."SPONSOR" ("ID_SPONSOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "ABIR"."CLIENT" ADD PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CREATEUR
--------------------------------------------------------

  ALTER TABLE "ABIR"."CREATEUR" ADD PRIMARY KEY ("ID_CREATEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEVELOPPER
--------------------------------------------------------

  ALTER TABLE "ABIR"."DEVELOPPER" ADD CONSTRAINT "PK_DEVELOPPER" PRIMARY KEY ("ID_CREATEUR", "ID_PROJET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "ABIR"."EMPLOYE" ADD PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FINANCER
--------------------------------------------------------

  ALTER TABLE "ABIR"."FINANCER" ADD CONSTRAINT "PK_FINANCER" PRIMARY KEY ("ID_SPONSOR", "ID_PROJET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIEL
--------------------------------------------------------

  ALTER TABLE "ABIR"."MATERIEL" ADD PRIMARY KEY ("ID_MATERIEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJET
--------------------------------------------------------

  ALTER TABLE "ABIR"."PROJET" ADD PRIMARY KEY ("ID_PROJET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPONSOR
--------------------------------------------------------

  ALTER TABLE "ABIR"."SPONSOR" ADD PRIMARY KEY ("ID_SPONSOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "ABIR"."CLIENT" ADD CONSTRAINT "FK_CLIENT_EMPLOYE" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "ABIR"."EMPLOYE" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEVELOPPER
--------------------------------------------------------

  ALTER TABLE "ABIR"."DEVELOPPER" ADD CONSTRAINT "FK_DEV_CREATEUR" FOREIGN KEY ("ID_CREATEUR")
	  REFERENCES "ABIR"."CREATEUR" ("ID_CREATEUR") ENABLE;
  ALTER TABLE "ABIR"."DEVELOPPER" ADD CONSTRAINT "FK_DEV_PROJET" FOREIGN KEY ("ID_PROJET")
	  REFERENCES "ABIR"."PROJET" ("ID_PROJET") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FINANCER
--------------------------------------------------------

  ALTER TABLE "ABIR"."FINANCER" ADD CONSTRAINT "FK_FIN_PROJET" FOREIGN KEY ("ID_PROJET")
	  REFERENCES "ABIR"."PROJET" ("ID_PROJET") ENABLE;
  ALTER TABLE "ABIR"."FINANCER" ADD CONSTRAINT "FK_FIN_SPONSOR" FOREIGN KEY ("ID_SPONSOR")
	  REFERENCES "ABIR"."SPONSOR" ("ID_SPONSOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATERIEL
--------------------------------------------------------

  ALTER TABLE "ABIR"."MATERIEL" ADD CONSTRAINT "FK_MATERIEL_PROJET" FOREIGN KEY ("ID_PROJET")
	  REFERENCES "ABIR"."PROJET" ("ID_PROJET") ENABLE;
